# Set your API keys
openai.api_key = "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"
weather_api_key = "74e04b0ffe2c41d99d251314241608"
news_api_key = "B21b5b0c69c942a7b7f7ec2c7eed7623"
bing_search_api_key = "9b35bdf1013648ea9f2e3e03324bbef3"